Надо подкачаться
htmlacademy-javascript/2254951-kekstagram-1 pull request #13
Opened 2024-04-01 10:36 UTC by ilianagis

2024-04-01 11:12 UTC, wonderjs requested changes
Осталось доработать только один момент:
[3.5.](https://up.htmlacademy.ru/javascript-individual/1/project/kekstagram#kekstagram-3-5) Если при отправке данных произошла ошибка запроса, нужно показать соответствующее сообщение. Сообщение должно исчезать после нажатия на кнопку .error__button, по нажатию на клавишу Esc и по клику на произвольную область экрана за пределами блока с сообщением. В таком случае вся введённая пользователем информация сохраняется, чтобы у него была возможность отправить форму повторно.
Те при нажатии на Esc модалка с ошибкой закрыться должна, а модалка с картинкой нет. Сейчас в этом случае закрываются обе

Можно (не обязательно сейчас) подумать в сторону того, чтобы оставить по одному обработчику на Esc и клик для document в случае показа модалок с ошибкой и успехом.

2024-04-01 11:12 UTC, wonderjs commented on js/main.js
> +//import { images } from './data.js';
Модуль data можно уже удалить и убрать тут импорт

2024-04-01 11:12 UTC, wonderjs commented on js/message.js
> +  successContainer.style.zIndex = 100;
Зачем z-index?

2024-04-01 11:12 UTC, wonderjs commented on js/message.js
> +const onErrorModalEscKeydown = (evt) => {
Лучше будет `onDocumentWithErrorKeydown`

2024-04-01 11:12 UTC, wonderjs commented on js/message.js
> +const onWindowWithErrorClick = (evt) => {
`onDocumentWithErrorClick`

2024-04-01 11:12 UTC, wonderjs commented on js/message.js
> +const onSuccessModalEscKeydown = (evt) => {
`onDocumentWithSuccessKeydown`

2024-04-01 11:12 UTC, wonderjs commented on js/message.js
> +const onSuccessModalWindowClick = (evt) => {
`onDocumentWithSuccessClick`

2024-04-02 16:56 UTC, wonderjs commented on js/form.js
> +  if (closeErrorModal) {
closeErrorModal это функция, она всегда будет существовать, значит условие под else никогда не выполнится. Тебе нужно проверить есть ли в доме элемент с модалкой ошибки.

2024-04-02 16:56 UTC, wonderjs commented on js/form.js
> +export { onFormSubmit, closeModal, onDocumentKeydown };
а зачем в экспорт добавила onDocumentKeydown? Экспериментировала и не удалила?

2024-04-02 16:57 UTC, merged

2024-04-02 17:20 UTC, ilianagis commented on js/form.js
> +export { onFormSubmit, closeModal, onDocumentKeydown };
да, сейчас удалю) очень много экспериментировала сегодня и не заметила ))